nelson
fjmn2001/ddd_in_php_from_zero pull request #18
Opened 2020-08-12 19:01 UTC by nelsonjc28

2020-08-12 19:16 UTC, fjmn2001 requested changes
Cambios requeridos

2020-08-12 19:16 UTC, fjmn2001 commented on apps/francisco/backend/public/index.php
> +$kernel = new NelsonBackendKernel($_SERVER['APP_ENV'], (bool) $_SERVER['APP_DEBUG']);
Solo debes editar tus propios archivos.

2020-08-12 19:16 UTC, fjmn2001 commented on .env.example
> -APP_SECRET=secret
Este archivo no se debe borrar

2020-08-12 21:36 UTC, nelsonjc28 commented on apps/francisco/backend/public/index.php
> +$kernel = new NelsonBackendKernel($_SERVER['APP_ENV'], (bool) $_SERVER['APP_DEBUG']);
corregido

2020-08-12 21:37 UTC, nelsonjc28 commented on .env.example
> -APP_SECRET=secret
lo agregue nuevamente

2020-08-13 02:15 UTC, fjmn2001 approved these changes
Listo Nelson

2020-08-13 02:16 UTC, merged