Jose changes 12/08/2020
fjmn2001/ddd_in_php_from_zero pull request #22
Opened 2020-08-12 21:42 UTC by Josequiloz10

2020-08-13 02:13 UTC, fjmn2001 requested changes
José, changes required

2020-08-13 02:13 UTC, fjmn2001 commented on composer.json
> +        "phpunit/phpunit": "^7.5"
José, aún tel falta terminar de correr composer para instalar el faker

2020-08-13 12:54 UTC, Josequiloz10 commented on composer.json
> +        "phpunit/phpunit": "^7.5"
@fjmn2001 Listo Sr.

2020-08-19 16:05 UTC, fjmn2001 approved these changes
Listo Jose

2020-08-19 16:05 UTC, merged